ALTER TABLE gallery_items ADD COLUMN IF NOT EXISTS width INTEGER;
ALTER TABLE gallery_items ADD COLUMN IF NOT EXISTS height INTEGER;
ALTER TABLE gallery_items ADD COLUMN IF NOT EXISTS resource_type VARCHAR(50);
