"use client";

import React, { useState, useEffect } from "react";
import {
  Download,
  Trash2,
  FileText,
  Clock,
  CheckCircle2,
  RefreshCw,
} from "lucide-react";
import { cn } from "@/lib/utils";
import { useToastStore } from "@/lib/toastStore";
import { EXPORT_HISTORY_INITIAL, ExportHistoryLogItem } from "@/lib/reportsData";

export default function ExportHistory() {
  const { addToast } = useToastStore();
  const [history, setHistory] = useState<ExportHistoryLogItem[]>([]);
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
    const stored = localStorage.getItem("eventos_exports_history");
    if (stored) {
      try {
        setHistory(JSON.parse(stored));
      } catch {
        setHistory(EXPORT_HISTORY_INITIAL);
      }
    } else {
      setHistory(EXPORT_HISTORY_INITIAL);
      localStorage.setItem("eventos_exports_history", JSON.stringify(EXPORT_HISTORY_INITIAL));
    }
  }, []);

  const saveHistory = (updated: ExportHistoryLogItem[]) => {
    setHistory(updated);
    localStorage.setItem("eventos_exports_history", JSON.stringify(updated));
  };

  const handleDelete = (id: string) => {
    const updated = history.filter((h) => h.id !== id);
    saveHistory(updated);
    addToast("Export history item removed.", "success");
  };

  const handleDownloadAgain = (item: ExportHistoryLogItem) => {
    addToast(`Re-downloading ${item.module} report (${item.format})...`, "info");
    setTimeout(() => {
      // Simulate file download
      const content = `Re-download generated ledger metadata for ID: ${item.id}\nExported by: ${item.generatedBy}\nFormat: ${item.format}`;
      const blob = new Blob([content], { type: "text/plain;charset=utf-8;" });
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.setAttribute("href", url);
      link.setAttribute("download", `redownload_${item.id}.${item.format.toLowerCase()}`);
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);

      addToast("Download complete!", "success");
    }, 800);
  };

  if (!mounted) return null;

  return (
    <div className="space-y-4">
      <h3 className="text-xs font-black uppercase text-zinc-550 tracking-wider">Historical Exports Log</h3>
      {history.length === 0 ? (
        <div className="p-12 border border-zinc-850 bg-zinc-950/20 rounded-2xl text-center space-y-2">
          <Download size={32} className="mx-auto text-zinc-700" />
          <p className="text-xs text-zinc-500 font-bold">No historical exports found in workspace ledger.</p>
        </div>
      ) : (
        <div className="border border-zinc-850 rounded-2xl bg-zinc-950/20 overflow-hidden">
          <div className="overflow-x-auto scrollbar-thin">
            <table className="w-full text-left border-collapse text-xs">
              <thead className="bg-zinc-950/40 text-[9px] font-black uppercase tracking-wider text-zinc-550 border-b border-zinc-850/60">
                <tr>
                  <th className="px-5 py-3">Report ID</th>
                  <th className="px-5 py-3">Export Target</th>
                  <th className="px-5 py-3 text-center">Format</th>
                  <th className="px-5 py-3 text-center">File Size</th>
                  <th className="px-5 py-3 text-center">Date Generated</th>
                  <th className="px-5 py-3 text-center">Generated By</th>
                  <th className="px-5 py-3 text-center">Status</th>
                  <th className="px-5 py-3 text-right">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-zinc-850/40">
                {history.map((item) => (
                  <tr key={item.id} className="hover:bg-zinc-900/10 transition-colors group">
                    <td className="px-5 py-3.5 font-mono text-zinc-500 font-bold">{item.id}</td>
                    <td className="px-5 py-3.5 font-bold text-zinc-200">{item.module}</td>
                    <td className="px-5 py-3.5 text-center font-semibold text-zinc-400">
                      <span className="px-1.5 py-0.5 rounded text-[8px] font-black uppercase bg-zinc-900 border border-zinc-850 text-purple-400">
                        {item.format}
                      </span>
                    </td>
                    <td className="px-5 py-3.5 text-center font-semibold text-zinc-400">{item.size}</td>
                    <td className="px-5 py-3.5 text-center font-semibold text-zinc-500 font-mono text-[10px]">
                      {new Date(item.date).toLocaleDateString()}
                    </td>
                    <td className="px-5 py-3.5 text-center font-semibold text-zinc-400">{item.generatedBy}</td>
                    <td className="px-5 py-3.5 text-center">
                      <span className="px-2 py-0.5 rounded-md text-[8px] font-black uppercase border tracking-wider bg-emerald-500/10 text-emerald-400 border-emerald-500/20">
                        Ready
                      </span>
                    </td>
                    <td className="px-5 py-3.5 text-right">
                      <div className="flex justify-end items-center gap-2">
                        <button
                          onClick={() => handleDownloadAgain(item)}
                          className="p-1 text-zinc-500 hover:text-purple-400 transition-colors cursor-pointer"
                          title="Download Again"
                        >
                          <Download size={13} />
                        </button>
                        <button
                          onClick={() => handleDelete(item.id)}
                          className="p-1 text-zinc-700 hover:text-red-500 transition-colors cursor-pointer opacity-0 group-hover:opacity-100"
                          title="Delete History"
                        >
                          <Trash2 size={13} />
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </div>
  );
}
