-- Make bookings.event_id nullable to allow bookings created without a linked event
-- (e.g. for invoice-only workflows or bookings created before event assignment)

-- Drop FK constraint (name generated by PostgreSQL default naming)
DO $$
DECLARE
    constraint_name TEXT;
BEGIN
    SELECT tc.constraint_name
    INTO constraint_name
    FROM information_schema.table_constraints AS tc
    JOIN information_schema.key_column_usage AS kcu
        ON tc.constraint_name = kcu.constraint_name
    WHERE tc.table_name = 'bookings'
      AND tc.constraint_type = 'FOREIGN KEY'
      AND kcu.column_name = 'event_id'
    LIMIT 1;

    IF constraint_name IS NOT NULL THEN
        EXECUTE 'ALTER TABLE bookings DROP CONSTRAINT ' || quote_ident(constraint_name);
    END IF;
END $$;

-- Remove NOT NULL constraint from event_id
ALTER TABLE bookings ALTER COLUMN event_id DROP NOT NULL;

-- Re-add FK as nullable (optional reference)
ALTER TABLE bookings
    ADD CONSTRAINT fk_bookings_event_id
    FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE SET NULL;
